{"seeAlsoSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/extraAppContent"],"generated":true,"title":"Representation"}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"property","title":"originalOffering","navigatorTitle":[{"text":"originalOffering","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"JoynedMobileSDK"}],"role":"symbol","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingResponse(py)originalOffering","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"originalOffering"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"A dictionary containing the original offering data"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedofferingresponse\/originaloffering"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedofferingresponse\/originaloffering"]}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/originalOffering"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"originalOffering","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse/extraAppContent":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"extraAppContent","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/extraAppContent","title":"extraAppContent","url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse\/extraappcontent","abstract":[{"text":"A dictionary containing the extra appliction data, may be used for in-app navigation logic","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"extraAppContent"}],"type":"topic","role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","role":"collection","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse/originalOffering":{"navigatorTitle":[{"kind":"identifier","text":"originalOffering"}],"title":"originalOffering","url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse\/originaloffering","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"originalOffering","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/originalOffering","abstract":[{"type":"text","text":"A dictionary containing the original offering data"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedOfferingResponse"}],"url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoynedOfferingResponse"}],"role":"symbol","kind":"symbol","title":"JoynedOfferingResponse"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"kind":"article","abstract":[],"title":"Getting Started with Joyned mobile SDK","type":"topic","url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"originalOffering"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"originalOffering","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"generated":true,"title":"Representation","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse\/extraAppContent"]}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" * "},{"text":"originalOffering","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1extraAppContent\/title","value":"extraAppContent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1extraAppContent\/fragments","value":[{"text":"extraAppContent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1originalOffering\/title","value":"originalOffering"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse~1originalOffering\/fragments","value":[{"text":"originalOffering","kind":"identifier"}]},{"op":"replace","value":"JoynedOfferingResponse","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse\/fragments","value":[{"text":"JoynedOfferingResponse","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}