{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"originalOffering"},{"text":": ","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest"]]},"kind":"symbol","seeAlsoSections":[{"title":"Representation","generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/extraAppContent"]}],"abstract":[{"text":"A dictionary containing the original offering data","type":"text"}],"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedofferingrequest\/originaloffering"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/joynedmobilesdk\/joynedofferingrequest\/originaloffering"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/originalOffering","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"JoynedMobileSDK"}],"title":"originalOffering","symbolKind":"property","navigatorTitle":[{"text":"originalOffering","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"originalOffering","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"}],"roleHeading":"Instance Property","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest(py)originalOffering"},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest":{"type":"topic","url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedOfferingRequest","kind":"identifier"}],"navigatorTitle":[{"text":"JoynedOfferingRequest","kind":"identifier"}],"title":"JoynedOfferingRequest","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest/originalOffering":{"url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest\/originaloffering","role":"symbol","kind":"symbol","title":"originalOffering","type":"topic","abstract":[{"text":"A dictionary containing the original offering data","type":"text"}],"navigatorTitle":[{"text":"originalOffering","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"originalOffering","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/originalOffering"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest/extraAppContent":{"url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest\/extraappcontent","role":"symbol","kind":"symbol","title":"extraAppContent","type":"topic","abstract":[{"type":"text","text":"A dictionary containing the extra appliction data, may be used for in-app navigation logic"}],"navigatorTitle":[{"text":"extraAppContent","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extraAppContent"},{"kind":"text","text":": "},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/extraAppContent"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"kind":"article","abstract":[],"title":"Getting Started with Joyned mobile SDK","type":"topic","url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","role":"collection","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"originalOffering","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"originalOffering","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Representation","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest\/extraAppContent"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" * "},{"kind":"identifier","text":"originalOffering"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"JoynedOfferingRequest","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/title"},{"op":"replace","value":[{"text":"JoynedOfferingRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1originalOffering\/title","value":"originalOffering","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1originalOffering\/fragments","value":[{"kind":"identifier","text":"originalOffering"}]},{"value":"extraAppContent","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1extraAppContent\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest~1extraAppContent\/fragments","value":[{"kind":"identifier","text":"extraAppContent"}]}]}]}