{"sections":[],"metadata":{"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"clearScreensBlackList","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Type Method","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedSDK(cm)clearScreensBlackList","navigatorTitle":[{"kind":"identifier","text":"clearScreensBlackList"}],"role":"symbol","modules":[{"name":"JoynedMobileSDK"}],"title":"clearScreensBlackList()"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearScreensBlackList","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/clearScreensBlackList()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Use this method to clear the invalid screen names from the system black list","type":"text"}],"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/clearscreensblacklist()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/clearscreensblacklist()"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"title":"SDK Screen Validation","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(WhiteList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(WhiteList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(BlackList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(BlackList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst"]}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","title":"Getting Started with Joyned mobile SDK"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/clearScreensBlackList()":{"abstract":[{"type":"text","text":"Use this method to clear the invalid screen names from the system black list"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/clearscreensblacklist()","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/clearScreensBlackList()","kind":"symbol","title":"clearScreensBlackList()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearScreensBlackList","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"clearScreensBlackList","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/append(WhiteList:)":{"navigatorTitle":[{"kind":"identifier","text":"appendWithWhiteList:"}],"role":"symbol","title":"append(WhiteList:)","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(WhiteList:)","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/append(whitelist:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"append","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"WhiteList"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Use this method to add a new screen name to the system white list"},{"text":" ","type":"text"},{"text":"On screens which appear in the whitelist the Joyned mobile SDK will present it’s floating content,","type":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"role":"collection","title":"JoynedMobileSDK","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","url":"\/documentation\/joynedmobilesdk","kind":"symbol","abstract":[{"type":"text","text":"We help people book together. With a better booking experience, better business results"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/append(BlackList:)":{"abstract":[{"type":"text","text":"Use this method to add a new screen name to the system black list"},{"type":"text","text":" "},{"type":"text","text":"On screens which appear in the blacklist the Joyned mobile SDK will not present it’s floating content,"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/append(blacklist:)","title":"append(BlackList:)","type":"topic","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(BlackList:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"append","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"BlackList"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"appendWithBlackList:"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/remove(BlackList:)":{"abstract":[{"type":"text","text":"Use this method to remove a  screen name to the system black list"},{"type":"text","text":" "},{"text":"On screens which appear in the blacklist the Joyned mobile SDK will not present it’s floating content,","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/remove(blacklist:)","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(BlackList:)","kind":"symbol","title":"remove(BlackList:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"BlackList"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"removeWithBlackList:"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}],"role":"symbol","title":"JoynedSDK","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","url":"\/documentation\/joynedmobilesdk\/joynedsdk","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedSDK"}],"kind":"symbol","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/remove(WhiteList:)":{"abstract":[{"text":"Use this method to remove a screen name to the system white list","type":"text"},{"type":"text","text":" "},{"type":"text","text":"On screens which appear in the whitelist the Joyned mobile SDK will present it’s floating content,"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/remove(whitelist:)","title":"remove(WhiteList:)","type":"topic","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(WhiteList:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"WhiteList"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"removeWithWhiteList:","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/screen_llst":{"abstract":[{"type":"text","text":"Joyned Mobile SDK screen change monitor"}],"url":"\/documentation\/joynedmobilesdk\/screen_llst","title":"Screen Validation Controls","type":"topic","kind":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","role":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"clearScreensBlackList","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"clearScreensBlackList","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"title":"SDK Screen Validation","generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(WhiteList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(WhiteList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/append(BlackList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/remove(BlackList:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"clearScreensBlackList","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1clearScreensBlackList()\/title","value":"clearScreensBlackList"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1clearScreensBlackList()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"clearScreensBlackList","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(WhiteList:)\/title","value":"appendWithWhiteList:","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(WhiteList:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"appendWithWhiteList:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(BlackList:)\/title","value":"appendWithBlackList:"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1append(BlackList:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"appendWithBlackList:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"removeWithBlackList:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(BlackList:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(BlackList:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"removeWithBlackList:","kind":"identifier"}]},{"value":"JoynedSDK","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","op":"replace"},{"op":"replace","value":[{"text":"JoynedSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(WhiteList:)\/title","value":"removeWithWhiteList:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"removeWithWhiteList:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1remove(WhiteList:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}