{"seeAlsoSections":[{"generated":true,"title":"SDK UI Controls","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/hideDisplay()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/showDisplay()"]}],"metadata":{"symbolKind":"method","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedSDK(cm)minimizeDisplay","modules":[{"name":"JoynedMobileSDK"}],"role":"symbol","title":"minimizeDisplay()","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"minimizeDisplay","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"minimizeDisplay"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimizeDisplay"},{"kind":"text","text":"()"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"Works the same as if thw user taped on the appropriate button in the display","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Use this method to trigger a minimize action on the floating SDK UI elements,","type":"text"}],"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/minimizedisplay()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdk\/minimizedisplay()"]}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/minimizeDisplay()"},"sections":[],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/showDisplay()":{"kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/showdisplay()","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/showDisplay()","abstract":[{"type":"text","text":"Use this method to make the system show the floating SDK UI elements, if they have been hidden before"}],"role":"symbol","title":"showDisplay()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showDisplay"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"showDisplay"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/hideDisplay()":{"kind":"symbol","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/hideDisplay()","abstract":[{"type":"text","text":"Use this method to make the system hide the floating SDK UI elements"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk\/hidedisplay()","role":"symbol","title":"hideDisplay()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hideDisplay"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"hideDisplay","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"kind":"article","abstract":[],"title":"Getting Started with Joyned mobile SDK","type":"topic","url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK/minimizeDisplay()":{"kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedsdk\/minimizedisplay()","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/minimizeDisplay()","abstract":[{"type":"text","text":"Use this method to trigger a minimize action on the floating SDK UI elements,"}],"role":"symbol","title":"minimizeDisplay()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimizeDisplay"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"minimizeDisplay"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","role":"collection","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"title":"JoynedSDK","kind":"symbol","navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedSDK","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"minimizeDisplay","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"minimizeDisplay"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"SDK UI Controls","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/hideDisplay()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK\/showDisplay()"],"generated":true}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"minimizeDisplay","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"showDisplay","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1showDisplay()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"showDisplay"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1showDisplay()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1hideDisplay()\/title","value":"hideDisplay"},{"value":[{"text":"+ ","kind":"text"},{"text":"hideDisplay","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1hideDisplay()\/fragments","op":"replace"},{"value":"minimizeDisplay","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1minimizeDisplay()\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"minimizeDisplay","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK~1minimizeDisplay()\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","value":"JoynedSDK","op":"replace"},{"value":[{"text":"JoynedSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments"}]}]}