{"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"]]},"abstract":[{"type":"text","text":"Called when the SDK failed to activate"}],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidFailToActivate()","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidfailtoactivate()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidfailtoactivate()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@JoynedMobileSDK@objc(pl)JoynedSDKDelegate(im)mobileSDKDidFailToActivate","navigatorTitle":[{"kind":"identifier","text":"mobileSDKDidFailToActivate"}],"modules":[{"name":"JoynedMobileSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mobileSDKDidFailToActivate"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","title":"mobileSDKDidFailToActivate()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mobileSDKDidFailToActivate"},{"kind":"text","text":"()"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","abstract":[{"type":"text","text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"JoynedSDKDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"kind":"symbol","title":"JoynedSDKDelegate","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","title":"Getting Started with Joyned mobile SDK"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"role":"collection","title":"JoynedMobileSDK","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","url":"\/documentation\/joynedmobilesdk","kind":"symbol","abstract":[{"type":"text","text":"We help people book together. With a better booking experience, better business results"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKDidFailToActivate()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mobileSDKDidFailToActivate","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidFailToActivate()","abstract":[{"text":"Called when the SDK failed to activate","type":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidfailtoactivate()","type":"topic","title":"mobileSDKDidFailToActivate()","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mobileSDKDidFailToActivate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mobileSDKDidFailToActivate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mobileSDKDidFailToActivate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"mobileSDKDidFailToActivate","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title","value":"JoynedSDKDelegate"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments","value":[{"kind":"identifier","text":"JoynedSDKDelegate"}],"op":"replace"},{"op":"replace","value":"mobileSDKDidFailToActivate","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidFailToActivate()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"mobileSDKDidFailToActivate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidFailToActivate()\/fragments"}]}]}