{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/gettingstarted"]},{"paths":["\/documentation\/joynedmobilesdk\/gettingstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK"]]},"metadata":{"modules":[{"name":"JoynedMobileSDK"}],"title":"Getting Started with Joyned mobile SDK","role":"collectionGroup","roleHeading":"API Collection"},"topicSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"],"title":"Essentials"},{"title":"Hosted Joyned UI","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/hosted_ui","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"]},{"title":"Invetation link API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/invitation_links"]},{"title":"Offering Related API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/offering","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/transaction","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest"],"title":"Transaction report API"},{"title":"Advance usage API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/advance"]},{"title":"Objective-C Utilities","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_throw_objc(_:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_try_objc(_:_:_:)"]},{"title":"UIKit Utilities","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/UIKit\/UIWindow","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/UIKit\/UIViewController"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedAreaComputation"],"title":"Type Alias"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSample"]}],"sections":[],"kind":"article","references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedAreaComputation":{"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedAreaComputation","kind":"identifier"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedAreaComputation","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedareacomputation","role":"symbol","navigatorTitle":[{"text":"JoynedAreaComputation","kind":"identifier"}],"abstract":[{"type":"text","text":"A helper type used for dynamic drag area computations"}],"title":"JoynedAreaComputation"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"title":"JoynedSDK","kind":"symbol","navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedSDK","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/j_try_objc(_:_:_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"j_try_objc"},{"text":"(() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":", (","kind":"text"},{"text":"NSException","preciseIdentifier":"c:objc(cs)NSException","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", () -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_try_objc(_:_:_:)","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/j_try_objc(_:_:_:)","role":"symbol","navigatorTitle":[{"text":"j_try_objc","kind":"identifier"}],"title":"j_try_objc(_:_:_:)","abstract":[{"type":"text","text":"Execute Swift code that could generate an Objective-C exception in here to catch and handle it gracefully (ie don’t crash)"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/UIKit/UIViewController":{"type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"identifier"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/UIKit\/UIViewController","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/uikit\/uiviewcontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIViewController"}],"abstract":[{"type":"text","text":"Public extensions of JoynedMobileSDK for simplier code usage"}],"title":"UIViewController"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/j_throw_objc(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"j_throw_objc","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSException","text":"NSException"},{"text":")","kind":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_throw_objc(_:)","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/j_throw_objc(_:)","role":"symbol","navigatorTitle":[{"text":"j_throw_objc","kind":"identifier"}],"title":"j_throw_objc(_:)","abstract":[{"type":"text","text":"Throws an Objective-C exception"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"title":"JoynedSDKDelegate","kind":"symbol","navigatorTitle":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedSDKDelegate","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/advance":{"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/advance","kind":"article","url":"\/documentation\/joynedmobilesdk\/advance","role":"article","abstract":[{"type":"text","text":"Extra options to configure SDK sub-elements"}],"title":"Advance SDK configuration"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/global_delegate":{"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","kind":"article","url":"\/documentation\/joynedmobilesdk\/global_delegate","role":"article","title":"Global Delegate","abstract":[{"type":"text","text":"Joyned mobile SDK provides several intervention hooks via the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},{"type":"text","text":" protocol"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/transaction":{"type":"topic","role":"article","url":"\/documentation\/joynedmobilesdk\/transaction","title":"Report transaction","kind":"article","abstract":[{"text":"API to make joyned is aware of all purchase transactions processed by your application.","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/transaction"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/screen_llst":{"title":"Screen Validation Controls","kind":"article","url":"\/documentation\/joynedmobilesdk\/screen_llst","type":"topic","role":"article","abstract":[{"type":"text","text":"Joyned Mobile SDK screen change monitor"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/offering":{"kind":"article","abstract":[{"type":"text","text":"API for interacting with JoynedMobileSDK offerings"}],"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/offering","url":"\/documentation\/joynedmobilesdk\/offering","title":"Offering handling API","role":"article"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton","abstract":[],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","type":"topic","title":"JoynedButton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedButton"}],"navigatorTitle":[{"kind":"identifier","text":"JoynedButton"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/UIKit/UIWindow":{"type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/UIKit\/UIWindow","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/uikit\/uiwindow","role":"symbol","navigatorTitle":[{"text":"UIWindow","kind":"identifier"}],"abstract":[{"type":"text","text":"Public extensions of JoynedMobileSDK for simplier code usage"}],"title":"UIWindow"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedTransactionRequest":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"JoynedTransactionRequest","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"JoynedTransactionRequest","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest","title":"JoynedTransactionRequest","url":"\/documentation\/joynedmobilesdk\/joynedtransactionrequest","role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSample":{"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSample","kind":"article","url":"\/documentation\/joynedmobilesdk\/joynedsample","role":"sampleCode","title":"Sample code - Voyage App","abstract":[{"type":"text","text":"Integrate JoynedMobileSDK into an iOS app for booking and ordering togather."}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest":{"type":"topic","url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedOfferingRequest","kind":"identifier"}],"navigatorTitle":[{"text":"JoynedOfferingRequest","kind":"identifier"}],"title":"JoynedOfferingRequest","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","role":"collection","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/invitation_links":{"title":"Joyned Session invitation links","kind":"article","abstract":[{"text":"Handle supported deeplinks for Joyned content","type":"text"}],"type":"topic","url":"\/documentation\/joynedmobilesdk\/invitation_links","role":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/invitation_links"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/hosted_ui":{"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/hosted_ui","kind":"article","url":"\/documentation\/joynedmobilesdk\/hosted_ui","role":"article","abstract":[{"type":"text","text":"Hosted Joyned UI"},{"text":" ","type":"text"},{"type":"text","text":"Joyned mobile SDK provides a few views which are ment to be used within application that hosts the SDK"}],"title":"Hosted UI"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedOfferingResponse"}],"url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoynedOfferingResponse"}],"role":"symbol","kind":"symbol","title":"JoynedOfferingResponse"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate":{"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate","abstract":[],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","type":"topic","title":"JoynedButtonDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedButtonDelegate"}],"navigatorTitle":[{"text":"JoynedButtonDelegate","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/activation":{"abstract":[{"type":"text","text":"There are several different ways to activate of the Joyned mobile SDK"}],"kind":"article","title":"Activation Methods","url":"\/documentation\/joynedmobilesdk\/activation","role":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/installation":{"title":"Library installation","role":"article","abstract":[{"text":"How to install this library","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","type":"topic","kind":"article","url":"\/documentation\/joynedmobilesdk\/installation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"title":"Essentials","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"]},{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/hosted_ui","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate"],"title":"Hosted Joyned UI"},{"title":"Invetation link API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/invitation_links"]},{"title":"Offering Related API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/offering","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse"]},{"title":"Transaction report API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/transaction","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedTransactionRequest"]},{"title":"Advance usage API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/advance"]},{"title":"Objective-C Utilities","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_throw_objc(_:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/j_try_objc(_:_:_:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSample"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":"JoynedSDK","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","op":"replace","value":[{"text":"JoynedSDK","kind":"identifier"}]},{"value":"j_try_objc","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_try_objc(_:_:_:)\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_try_objc(_:_:_:)\/fragments","op":"replace","value":[{"text":"j_try_objc","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_throw_objc(_:)\/title","value":"j_throw_objc","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1j_throw_objc(_:)\/fragments","op":"replace","value":[{"text":"j_throw_objc","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title","value":"JoynedSDKDelegate"},{"value":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title","op":"replace","value":"JoynedButton"},{"value":[{"text":"JoynedButton","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest\/title","value":"JoynedTransactionRequest"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedTransactionRequest\/fragments","value":[{"text":"JoynedTransactionRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/title","value":"JoynedOfferingRequest"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/fragments","value":[{"kind":"identifier","text":"JoynedOfferingRequest"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse\/title","value":"JoynedOfferingResponse","op":"replace"},{"op":"replace","value":[{"text":"JoynedOfferingResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse\/fragments"},{"value":"JoynedButtonDelegate","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/fragments","value":[{"text":"JoynedButtonDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}