{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/installation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/installation"]}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted"]]},"metadata":{"title":"Library installation","roleHeading":"Article","role":"article","modules":[{"name":"JoynedMobileSDK"}]},"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"tabNavigator","tabs":[{"title":"Swift package manager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"https:\/\/swift.org\/package-manager\/"},{"text":" is a tool for automating the distribution of Swift code and is integrated into the ","type":"text"},{"code":"swift","type":"codeVoice"},{"type":"text","text":" compiler."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once you have your Swift package set up, adding JoynedMobileSDK as a dependency is as easy as adding it to the "},{"code":"dependencies","type":"codeVoice"},{"text":" value of your ","type":"text"},{"code":"Package.swift","type":"codeVoice"},{"text":" or the Package list in Xcode.","type":"text"}]},{"type":"codeListing","code":["dependencies: [","    .package(url: \"https:\/\/github.com\/gamitee-dev\/ios-sdk-storage.git\", .upToNextMajor(from: \"1.0.0\"))","]"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"Normally you’ll want to depend on the ","type":"text"},{"type":"codeVoice","code":"Joyned"},{"text":" target:","type":"text"}]},{"code":[".product(name: \"JoynedMobileSDK\", package: \"JoynedMobileSDK\")"],"syntax":"swift","type":"codeListing"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"https:\/\/cocoapods.org","type":"reference"},{"text":" is a dependency manager for Cocoa projects.","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To install cocoapods via gem if needed"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Open terminal"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Type ","type":"text"},{"type":"codeVoice","code":"$ [sudo] gem install cocoapods"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Press enter"}]}]}]}]}],"type":"unorderedList"},{"inlineContent":[{"text":"For more usage and installation instructions, visit their website.","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To integrate Joyned into your Xcode project using CocoaPods, specify it in your "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":":"}]}]}]},{"type":"codeListing","code":["target ‘YOUR_PROJECT’ do","    …","    pod 'JoynedMobileSDK' , '~> 1.0.0'","end"],"syntax":"ruby"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"In the terminal run "},{"code":"pod install","type":"codeVoice"}],"type":"paragraph"},{"level":4,"text":"Note for Mac M1 users:","anchor":"Note-for-Mac-M1-users","type":"heading"},{"inlineContent":[{"type":"text","text":"Mac M1 architecture is not directly compatible with Cocoapods. If you encounter issues when installing pods, you can solve it by running:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"sudo arch -x86_64 gem install ffi","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"arch -x86_64 pod install","type":"text"},{"text":" ","type":"text"},{"text":"These commands install the ffi package, to load dynamically-linked libraries and let you run the pod install properly, and runs pod install with the proper architecture.","type":"text"}]}]}]}]}]}],"title":"Cocoa-pods"},{"title":"Manually","content":[{"type":"paragraph","inlineContent":[{"text":"If you prefer not to use any of the other dependency managers, you can integrate Joyned into your project manually by adding the XCFramework to the project.","type":"text"}]}]}]}]}],"sections":[],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","interfaceLanguage":"swift"},"kind":"article","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"How to install this library"}],"seeAlsoSections":[{"generated":true,"title":"Essentials","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"]}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"title":"JoynedSDKDelegate","kind":"symbol","navigatorTitle":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedSDKDelegate","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/activation":{"abstract":[{"type":"text","text":"There are several different ways to activate of the Joyned mobile SDK"}],"kind":"article","title":"Activation Methods","url":"\/documentation\/joynedmobilesdk\/activation","role":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","type":"topic"},"https://swift.org/package-manager/":{"url":"https:\/\/swift.org\/package-manager\/","identifier":"https:\/\/swift.org\/package-manager\/","title":"Swift Package Manager","type":"link","titleInlineContent":[{"text":"Swift Package Manager","type":"text"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"kind":"article","abstract":[],"title":"Getting Started with Joyned mobile SDK","type":"topic","url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup"},"https://cocoapods.org":{"type":"link","titleInlineContent":[{"type":"text","text":"CocoaPods"}],"title":"CocoaPods","url":"https:\/\/cocoapods.org","identifier":"https:\/\/cocoapods.org"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"title":"JoynedSDK","kind":"symbol","navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedSDK","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/global_delegate":{"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","kind":"article","url":"\/documentation\/joynedmobilesdk\/global_delegate","role":"article","title":"Global Delegate","abstract":[{"type":"text","text":"Joyned mobile SDK provides several intervention hooks via the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},{"type":"text","text":" protocol"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/screen_llst":{"title":"Screen Validation Controls","kind":"article","url":"\/documentation\/joynedmobilesdk\/screen_llst","type":"topic","role":"article","abstract":[{"type":"text","text":"Joyned Mobile SDK screen change monitor"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","role":"collection","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"],"title":"Essentials"}],"op":"replace"},{"value":"JoynedSDKDelegate","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments","value":[{"kind":"identifier","text":"JoynedSDKDelegate"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title","value":"JoynedSDK","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","value":[{"kind":"identifier","text":"JoynedSDK"}]}]}]}