{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@JoynedMobileSDK@objc(pl)JoynedButtonDelegate","navigatorTitle":[{"text":"JoynedButtonDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedButtonDelegate","kind":"identifier"}],"modules":[{"name":"JoynedMobileSDK"}],"symbolKind":"protocol","title":"JoynedButtonDelegate","role":"symbol","roleHeading":"Protocol"},"topicSections":[{"title":"Offering computations","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingFor:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForRaw:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForItem:)"]},{"title":"Notifications","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/willPresentMobileSDKContent()"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted"],["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"]]},"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(JoynedButtonDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedButtonDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedbuttondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedbuttondelegate"]}],"seeAlsoSections":[{"generated":true,"title":"Hosted Joyned UI","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/hosted_ui","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"]}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/hosted_ui":{"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/hosted_ui","kind":"article","url":"\/documentation\/joynedmobilesdk\/hosted_ui","role":"article","abstract":[{"type":"text","text":"Hosted Joyned UI"},{"text":" ","type":"text"},{"type":"text","text":"Joyned mobile SDK provides a few views which are ment to be used within application that hosts the SDK"}],"title":"Hosted UI"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate/joynedButton(_:productOfferingForRaw:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"joynedButton","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton","text":"JoynedButton"},{"kind":"text","text":", "},{"text":"productOfferingForRaw","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"text":"JoynedOfferingRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"joynedButton:productOfferingForRaw:","kind":"identifier"}],"abstract":[{"text":"Called when the User clicks the button, if the button is contained within a ","type":"text"},{"code":"UITableView","type":"codeVoice"},{"text":" and is visiable on screen","type":"text"},{"text":" ","type":"text"},{"text":"Asks for the relevent product offering, provides the index path associated with the button","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForRaw:)","kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingforraw:)","title":"joynedButton(_:productOfferingForRaw:)","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate":{"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate","abstract":[],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","type":"topic","title":"JoynedButtonDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedButtonDelegate"}],"navigatorTitle":[{"text":"JoynedButtonDelegate","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"kind":"article","abstract":[],"title":"Getting Started with Joyned mobile SDK","type":"topic","url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton","abstract":[],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","type":"topic","title":"JoynedButton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedButton"}],"navigatorTitle":[{"kind":"identifier","text":"JoynedButton"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate/joynedButton(_:productOfferingForItem:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"joynedButton","kind":"identifier"},{"kind":"text","text":"("},{"text":"JoynedButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton"},{"text":", ","kind":"text"},{"text":"productOfferingForItem","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"text":"JoynedOfferingRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"joynedButton:productOfferingForItem:"}],"abstract":[{"text":"Called when the User clicks the button, if the button is contained within a ","type":"text"},{"type":"codeVoice","code":"UICollectionView"},{"text":" and is visiable on screen","type":"text"},{"text":" ","type":"text"},{"text":"Asks for the relevent product offering, provides the index path associated with the button","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForItem:)","kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingforitem:)","type":"topic","title":"joynedButton(_:productOfferingForItem:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate/willPresentMobileSDKContent()":{"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/willpresentmobilesdkcontent()","abstract":[{"type":"text","text":"Called when the User clicks the button, before presenting any SDK content , after validations"}],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/willPresentMobileSDKContent()","type":"topic","title":"willPresentMobileSDKContent()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPresentMobileSDKContent"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"willPresentMobileSDKContent","kind":"identifier"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate/joynedButton(_:productOfferingFor:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"joynedButton"},{"text":"(","kind":"text"},{"text":"JoynedButton","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton"},{"kind":"text","text":", "},{"kind":"externalParam","text":"productOfferingFor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"JoynedOfferingRequest","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingRequest"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"joynedButton:productOfferingFor:","kind":"identifier"}],"abstract":[{"text":"Called when the User clicks the button,","type":"text"},{"text":" ","type":"text"},{"text":"Asks for the relevent product offering, provides the touch location associated with the button, in the window coordinatespace","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingFor:)","kind":"symbol","required":true,"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate\/joynedbutton(_:productofferingfor:)","title":"joynedButton(_:productOfferingFor:)","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","role":"collection","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"JoynedButtonDelegate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"kind":"identifier","text":"JoynedButtonDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"text":"JoynedButtonDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingFor:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForRaw:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/joynedButton(_:productOfferingForItem:)"],"title":"Offering computations"},{"title":"Notifications","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate\/willPresentMobileSDKContent()"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/hosted_ui","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"],"generated":true,"title":"Hosted Joyned UI"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JoynedButtonDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForRaw:)\/title","op":"replace","value":"joynedButton:productOfferingForRaw:"},{"value":[{"kind":"text","text":"- "},{"text":"joynedButton:productOfferingForRaw:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForRaw:)\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/title","value":"JoynedButtonDelegate","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/fragments","value":[{"text":"JoynedButtonDelegate","kind":"identifier"}],"op":"replace"},{"value":"JoynedButton","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","op":"replace","value":[{"text":"JoynedButton","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForItem:)\/title","value":"joynedButton:productOfferingForItem:"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingForItem:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"joynedButton:productOfferingForItem:"}]},{"value":"willPresentMobileSDKContent","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1willPresentMobileSDKContent()\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"willPresentMobileSDKContent","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1willPresentMobileSDKContent()\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingFor:)\/title","op":"replace","value":"joynedButton:productOfferingFor:"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate~1joynedButton(_:productOfferingFor:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"joynedButton:productOfferingFor:"}],"op":"replace"}]}]}