{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdkdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedsdkdelegate"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"seeAlsoSections":[{"generated":true,"title":"Essentials","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted"]]},"metadata":{"role":"symbol","modules":[{"name":"JoynedMobileSDK"}],"externalID":"c:@M@JoynedMobileSDK@objc(pl)JoynedSDKDelegate","title":"JoynedSDKDelegate","navigatorTitle":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedSDKDelegate","kind":"identifier"}],"symbolKind":"protocol"},"abstract":[{"type":"text","text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidActivateSuccessfully()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidFailToActivate()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidTriggerNavigation(for:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKLocaleForPresentingContent(given:)"]}],"relationshipsSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(JoynedSDKDelegate) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedSDKDelegate"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"See also:"}],"type":"strong"}],"type":"paragraph"},{"type":"links","style":"list","items":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate"]}],"kind":"content"}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"kind":"article","abstract":[],"title":"Getting Started with Joyned mobile SDK","type":"topic","url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","role":"collection","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKDidTriggerNavigation(for:)":{"kind":"symbol","abstract":[{"text":"Called when a user clicks on an offering within the Joyned UI, use this as a trigger for in-app navigation, for navigation details lokk into the payload object","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidTriggerNavigation(for:)","url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidtriggernavigation(for:)","role":"symbol","navigatorTitle":[{"text":"mobileSDKDidTriggerNavigationFor:","kind":"identifier"}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mobileSDKDidTriggerNavigation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JoynedOfferingResponse","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingResponse"},{"text":")","kind":"text"}],"title":"mobileSDKDidTriggerNavigation(for:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKLocaleForPresentingContent(given:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mobileSDKLocaleForPresentingContent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"given","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","abstract":[{"text":"An intervention location allowing to override the locale to be used when presenting SDK content on screen","type":"text"}],"title":"mobileSDKLocaleForPresentingContent(given:)","type":"topic","required":true,"navigatorTitle":[{"text":"mobileSDKLocaleForPresentingContentGiven:","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdklocaleforpresentingcontent(given:)","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKLocaleForPresentingContent(given:)","role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKDidFailToActivate()":{"kind":"symbol","abstract":[{"text":"Called when the SDK failed to activate","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidFailToActivate()","url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidfailtoactivate()","role":"symbol","navigatorTitle":[{"text":"mobileSDKDidFailToActivate","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mobileSDKDidFailToActivate","kind":"identifier"},{"text":"()","kind":"text"}],"title":"mobileSDKDidFailToActivate()"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/screen_llst":{"title":"Screen Validation Controls","kind":"article","url":"\/documentation\/joynedmobilesdk\/screen_llst","type":"topic","role":"article","abstract":[{"type":"text","text":"Joyned Mobile SDK screen change monitor"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDK":{"title":"JoynedSDK","kind":"symbol","navigatorTitle":[{"text":"JoynedSDK","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedSDK","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdk","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The main public access class to ther Joyned mobile SDK, use it to interact with the system"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/activation":{"abstract":[{"type":"text","text":"There are several different ways to activate of the Joyned mobile SDK"}],"kind":"article","title":"Activation Methods","url":"\/documentation\/joynedmobilesdk\/activation","role":"article","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","type":"topic"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/global_delegate":{"type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","kind":"article","url":"\/documentation\/joynedmobilesdk\/global_delegate","role":"article","title":"Global Delegate","abstract":[{"type":"text","text":"Joyned mobile SDK provides several intervention hooks via the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},{"type":"text","text":" protocol"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKDidActivateSuccessfully()":{"title":"mobileSDKDidActivateSuccessfully()","kind":"symbol","navigatorTitle":[{"text":"mobileSDKDidActivateSuccessfully","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mobileSDKDidActivateSuccessfully","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidactivatesuccessfully()","type":"topic","required":true,"role":"symbol","abstract":[{"type":"text","text":"Called when the SDK was activated successfully"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidActivateSuccessfully()"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/installation":{"title":"Library installation","role":"article","abstract":[{"text":"How to install this library","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","type":"topic","kind":"article","url":"\/documentation\/joynedmobilesdk\/installation"},"doc://co.joyned.mobile.JoynedMobileSDK/objc(pl)NSObject":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"title":"JoynedSDKDelegate","kind":"symbol","navigatorTitle":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedSDKDelegate","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"JoynedSDKDelegate","op":"replace"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"JoynedSDKDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidActivateSuccessfully()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidFailToActivate()","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidTriggerNavigation(for:)","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKLocaleForPresentingContent(given:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/installation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/activation","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/global_delegate","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/screen_llst","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDK"],"generated":true,"title":"Essentials"}]},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedSDKDelegate"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"mobileSDKDidTriggerNavigationFor:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidTriggerNavigation(for:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mobileSDKDidTriggerNavigationFor:"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidTriggerNavigation(for:)\/fragments"},{"value":"mobileSDKLocaleForPresentingContentGiven:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKLocaleForPresentingContent(given:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKLocaleForPresentingContent(given:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mobileSDKLocaleForPresentingContentGiven:"}],"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidFailToActivate()\/title","op":"replace","value":"mobileSDKDidFailToActivate"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidFailToActivate()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mobileSDKDidFailToActivate"}],"op":"replace"},{"value":"JoynedSDK","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDK\/fragments","value":[{"kind":"identifier","text":"JoynedSDK"}],"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidActivateSuccessfully()\/title","value":"mobileSDKDidActivateSuccessfully","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"mobileSDKDidActivateSuccessfully","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidActivateSuccessfully()\/fragments"},{"op":"replace","value":"JoynedSDKDelegate","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments","value":[{"kind":"identifier","text":"JoynedSDKDelegate"}]}]}]}