{"metadata":{"roleHeading":"Article","role":"article","title":"Offering handling API","modules":[{"name":"JoynedMobileSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/offering"},"seeAlsoSections":[{"generated":true,"title":"Offering Related API","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse"]}],"variants":[{"paths":["\/documentation\/joynedmobilesdk\/offering"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/joynedmobilesdk\/offering"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted"]]},"primaryContentSections":[{"content":[{"text":"Overview","type":"heading","level":2,"anchor":"Overview"},{"inlineContent":[{"text":"Joyned supports displaying diffrent offerings based on the application’s category it can be anything from an e-comerce product, to a hotel booking (this is why we use the term Offering)","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Joyned mobile sdk allows its integrator to interact with offerings in two seperate ways:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"adding offerings to the system"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"responding to user click on existing offerings in the Joyned UI","type":"text"}]}]}]},{"tabs":[{"content":[{"level":3,"text":"Adding a new Offering","anchor":"Adding-a-new-Offering","type":"heading"},{"type":"row","numberOfColumns":4,"columns":[{"size":1,"content":[{"inlineContent":[{"identifier":"screenshot_mobile_invitation_01.png","type":"image"}],"type":"paragraph"}]},{"size":3,"content":[{"inlineContent":[{"type":"text","text":"Joyned supports adding a new Offering only via the hosted UI."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Once a user taps on the relevent button the mobile SDK asks its host application for the offering information via a delegation protocol and processes it accordingly."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The delegation protocol in question is the "},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","isActive":true},{"type":"text","text":" you will need to"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The button delegate protocol covers three diffrent situations :"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Standalone"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Table \/ Collection view","type":"text"}]}]}],"type":"unorderedList"}]}]},{"inlineContent":[{"inlineContent":[{"text":"Standalone example:","type":"text"}],"type":"strong"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["import Foundation","import UIKit","","import JoynedMobileSDK","","class StandaloneViewController : UIViewController","{","    \/\/ MARK: - Properties","    internal var joynedButton : JoynedButton! {","        didSet { joynedButton.delegate = self }","    }","    internal var venue : Venue!","","    \/\/ MARK: - View LifeCycle","    override func viewDidLoad()","    {","        super.viewDidLoad()","        ","        joynedButton = JoynedSDK.generateJoynedButton(frame: CGRect(x: 100, y: 500, width: 70, height: 34), with: self)","        view.addSubview(button)","    }","}","extension StandaloneViewController : JoynedButtonDelegate","{","    func willPresentMobileSDKContent()","    {","        logger.debug()","    }","    ","    func joynedButton(_ button: JoynedButton, productOfferingFor location: CGPoint) -> JoynedOfferingRequest?","    {","        logger.debug()","        return encode(product: venue)","    }","    ","    private func encode(product item: Venue?) -> JoynedOfferingRequest?","    {","        guard let venue   = item              else { return nil }","        guard let product = venue.toPayload() else { return nil }","        guard let extra   = venue.toJSON()    else { return nil }","        return JoynedOfferingRequest(offeringString: product, extraString: extra)","    }","}"]},{"inlineContent":[{"inlineContent":[{"text":"Table \/ Collection example:","type":"text"}],"type":"strong"}],"type":"paragraph"},{"code":["import Foundation","import UIKit","","import JoynedMobileSDK","","class GroupViewController : UIViewController","{","    \/\/ MARK: - type - enum","    struct Constants","    {","        struct Identifier","        {","            private init() {}","        }","        private init() {}","    }","    ","    \/\/ MARK: - Properties","    private var selectedItem : Venue?","    ","    \/\/ MARK: - Properties","    private var dataSource : UICollectionViewDiffableDataSource<Int, Venue>!","    ","    \/\/ MARK: - @IBOutlet","    @IBOutlet      var  logoImageView : UIImageView!","    @IBOutlet weak var collectionView : UICollectionView! {","        didSet {","            collectionView.delegate = self","        }","    }","    ","    \/\/ MARK: - View LifeCycle","    override func viewDidLoad()","    {","        super.viewDidLoad()","        \/\/ Do any additional setup after loading the view.","        ","        title = String()","        navigationItem.titleView = logoImageView","        navigationItem.setHidesBackButton(true, animated: false)","        ","        registerVisualElements()","        configureVisualElements()","    }","}","\/\/ MARK: - Constants","fileprivate extension GroupViewController.Constants.Identifier","{","    static var   cell : String { \"DealsFeedCellIdentifier\"   }","    static var header : String { \"DealsFeedHeaderIdentifier\" }","    static var global : String { \"SearchHeaderIdentifier\"    }","}","\/\/ MARK: - Collection View setup","fileprivate extension GroupViewController","{","    private func registerVisualElements()","    {","        collectionView.register(ProductCollectionViewCell.classNib, forCellWithReuseIdentifier: Constants.Identifier.cell)","        collectionView.register(SearchHeaderView.classNib         , forSupplementaryViewOfKind: Constants.Identifier.global, withReuseIdentifier: Constants.Identifier.global)","    }","    private func configureVisualElements()","    {","        ","        dataSource = UICollectionViewDiffableDataSource<Int, Venue>(collectionView: collectionView) { (collectionView, indexPath, item) -> UICollectionViewCell? in","            ","            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: Constants.Identifier.cell, for: indexPath)","            ","            if let cell = cell as? ProductCollectionViewCell","            {","                cell.titleLabel.text        = item.productTitle","                cell.datesLabel.text        = \"\\(item.productDates.checkin) - \\(item.productDates.checkout)\"","                cell.descriptionLabel.text  = item.productDescription","                cell.locationLabel.text     = nil","                cell.priceLabel.text        = \"\\(item.productPrice.amount) \\(item.productPrice.currency)\"","                cell.imageView.image        = UIImage(named: item.productThumbnail)","                cell.joynedButton.delegate  = self","            }","            ","            return cell","        }","        dataSource?.supplementaryViewProvider = { (collectionView,kind,indexPath) -> UICollectionReusableView? in","            ","            guard kind == Constants.Identifier.global else { return nil }","            return collectionView.dequeueReusableSupplementaryView(","                ofKind: kind,","                withReuseIdentifier: Constants.Identifier.global,","                for: indexPath","            )","        }","    }","}","extension GroupViewController : JoynedButtonDelegate","{","    func willPresentMobileSDKContent()","    {","        logger.debug()","    }","    ","    func joynedButton(_ button: JoynedButton, productOfferingForItem indexPath: IndexPath) -> JoynedOfferingRequest?","    {","        return encode(product: dataSource.itemIdentifier(for: indexPath))","    }","    ","    private func encode(product item: Venue?) -> JoynedOfferingRequest?","    {","        guard let venue   = item              else { return nil }","        guard let product = venue.toPayload() else { return nil }","        guard let extra   = venue.toJSON()    else { return nil }","        \/\/ let extra: [String: Any] = [","        \/\/     \"itemLink\": \"https:\/\/voyage.joyned.app\/product\/1\",","        \/\/ ]","        return JoynedOfferingRequest(offeringString: product, extraString: extra)","    }","}",""],"syntax":"swift","type":"codeListing"}],"title":"Add offering"},{"content":[{"anchor":"In-App-navigation-in-response-to-user-action","level":3,"text":"In-App navigation in response to user action","type":"heading"},{"inlineContent":[{"text":"To support in-app navigation ","type":"text"},{"inlineContent":[{"type":"text","text":"Joyned mobile sdk"}],"type":"strong"},{"text":"  exposes a delegation method via its public accessd class.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"When user taps on an offering within the floating container the system extracts it’s data , wrapps it into a rsponse object and calls on its delegate object with the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidTriggerNavigation(for:)"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":""},{"type":"text","text":" "},{"text":"This is the only required method in the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate","isActive":true,"type":"reference"},{"text":" protocol.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"In-app navigation example:","type":"text"}]}]},{"type":"codeListing","code":["func mobileSDKDidTriggerNavigation(for navigationPayload: JoynedMobileSDK.JoynedOfferingResponse)","{","    logger.debug()","    guard let targetUrl = navigationPayload.directUrl      else { return }","    guard let keyWindow = UIApplication.shared.v_keyWindow else { return }","    ","    if let topVC = keyWindow.v_topViewController {","        topVC.tabBarController?.selectedIndex = 0","    }","    ","    if let topVC = keyWindow.v_topViewController {","        topVC.navigationController?.popToRootViewController(animated: true)","    }","    ","    guard let vc = keyWindow.v_topViewController             else { return }","    guard let dealsVC = vc as? DealsFeedViewController       else { return }","    guard let item = DataService.shared.item(for: targetUrl) else { return }","    ","    dealsVC.present(selected: item)","    ","    JoynedSDK.minimizeDisplay()","}"],"syntax":"swift"}],"title":"Respond to offering"}],"type":"tabNavigator"}],"kind":"content"}],"abstract":[{"type":"text","text":"API for interacting with JoynedMobileSDK offerings"}],"kind":"article","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"kind":"article","abstract":[],"title":"Getting Started with Joyned mobile SDK","type":"topic","url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate":{"title":"JoynedSDKDelegate","kind":"symbol","navigatorTitle":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedSDKDelegate","kind":"identifier"}],"url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Implement this to recive notifications on major actions taken by the SDK and affect its behavior"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedSDKDelegate/mobileSDKDidTriggerNavigation(for:)":{"kind":"symbol","abstract":[{"text":"Called when a user clicks on an offering within the Joyned UI, use this as a trigger for in-app navigation, for navigation details lokk into the payload object","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedSDKDelegate\/mobileSDKDidTriggerNavigation(for:)","url":"\/documentation\/joynedmobilesdk\/joynedsdkdelegate\/mobilesdkdidtriggernavigation(for:)","role":"symbol","navigatorTitle":[{"text":"mobileSDKDidTriggerNavigationFor:","kind":"identifier"}],"required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mobileSDKDidTriggerNavigation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JoynedOfferingResponse","kind":"typeIdentifier","preciseIdentifier":"c:@M@JoynedMobileSDK@objc(cs)JoynedOfferingResponse"},{"text":")","kind":"text"}],"title":"mobileSDKDidTriggerNavigation(for:)"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingRequest":{"type":"topic","url":"\/documentation\/joynedmobilesdk\/joynedofferingrequest","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoynedOfferingRequest","kind":"identifier"}],"navigatorTitle":[{"text":"JoynedOfferingRequest","kind":"identifier"}],"title":"JoynedOfferingRequest","kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","abstract":[]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","role":"collection","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk"},"screenshot_mobile_invitation_01.png":{"variants":[{"url":"\/images\/screenshot_mobile_invitation_01.png","traits":["1x","light"]}],"identifier":"screenshot_mobile_invitation_01.png","alt":"Joyned invitation mobile example 01","type":"image"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedOfferingResponse":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedOfferingResponse"}],"url":"\/documentation\/joynedmobilesdk\/joynedofferingresponse","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"JoynedOfferingResponse"}],"role":"symbol","kind":"symbol","title":"JoynedOfferingResponse"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButtonDelegate":{"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbuttondelegate","abstract":[],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButtonDelegate","type":"topic","title":"JoynedButtonDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedButtonDelegate"}],"navigatorTitle":[{"text":"JoynedButtonDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingRequest","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedOfferingResponse"],"generated":true,"title":"Offering Related API"}]},{"op":"replace","value":"JoynedSDKDelegate","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/title"},{"value":[{"text":"JoynedSDKDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate\/fragments"},{"op":"replace","value":"mobileSDKDidTriggerNavigationFor:","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidTriggerNavigation(for:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mobileSDKDidTriggerNavigationFor:","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedSDKDelegate~1mobileSDKDidTriggerNavigation(for:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/title","value":"JoynedOfferingRequest"},{"value":[{"text":"JoynedOfferingRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingRequest\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse\/title","value":"JoynedOfferingResponse"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedOfferingResponse\/fragments","op":"replace","value":[{"text":"JoynedOfferingResponse","kind":"identifier"}]},{"op":"replace","value":"JoynedButtonDelegate","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButtonDelegate\/fragments","value":[{"kind":"identifier","text":"JoynedButtonDelegate"}],"op":"replace"}]}]}