{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"]]},"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/isshadowenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/isshadowenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Determins if the card content should have a shadow outline or not, defaults to false"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@IBInspectable","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isShadowEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton(py)isShadowEnabled","roleHeading":"Instance Property","title":"isShadowEnabled","navigatorTitle":[{"text":"isShadowEnabled","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isShadowEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"JoynedMobileSDK"}],"role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"seeAlsoSections":[{"title":"Card UI Controls - Shadow","generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowColor","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOpacity","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius"]}],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","interfaceLanguage":"swift"},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/isShadowEnabled":{"navigatorTitle":[{"text":"isShadowEnabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isShadowEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Determins if the card content should have a shadow outline or not, defaults to false"}],"kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/isshadowenabled","type":"topic","title":"isShadowEnabled","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowOffset":{"navigatorTitle":[{"text":"shadowOffset","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shadowOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"text":"The offset  of the shadow used by the card UI, only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","isActive":true,"type":"reference"},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Zero by default."}],"kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowoffset","type":"topic","title":"shadowOffset","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowRadius":{"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius","abstract":[{"type":"text","text":"The radius of the shadow used by the card UI, only takes effect if the "},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","isActive":true},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Zero by default."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowradius","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"shadowRadius","navigatorTitle":[{"text":"shadowRadius","kind":"identifier"}],"role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowColor":{"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowColor","abstract":[{"text":"The color to be used for card UI shadow color, only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","isActive":true,"type":"reference"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Transperent by default."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowcolor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"title":"shadowColor","navigatorTitle":[{"kind":"identifier","text":"shadowColor"}],"role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","role":"collection","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"kind":"article","abstract":[],"title":"Getting Started with Joyned mobile SDK","type":"topic","url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowOpacity":{"navigatorTitle":[{"text":"shadowOpacity","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shadowOpacity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"abstract":[{"type":"text","text":"The opacity level of the shadow used by the card UI, only takes effect if the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Zero by default.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowopacity","type":"topic","title":"shadowOpacity","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOpacity"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton","abstract":[],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","type":"topic","title":"JoynedButton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedButton"}],"navigatorTitle":[{"kind":"identifier","text":"JoynedButton"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"isShadowEnabled","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isShadowEnabled","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowColor","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOpacity","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius"],"title":"Card UI Controls - Shadow","generated":true}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isShadowEnabled","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShadowEnabled\/title","op":"replace","value":"isShadowEnabled"},{"value":[{"text":"isShadowEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShadowEnabled\/fragments","op":"replace"},{"value":"shadowOffset","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOffset\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"shadowOffset"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOffset\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowRadius\/title","value":"shadowRadius","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowRadius\/fragments","op":"replace","value":[{"kind":"identifier","text":"shadowRadius"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowColor\/title","value":"shadowColor"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowColor\/fragments","value":[{"kind":"identifier","text":"shadowColor"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOpacity\/title","value":"shadowOpacity","op":"replace"},{"value":[{"kind":"identifier","text":"shadowOpacity"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOpacity\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title","value":"JoynedButton"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","value":[{"text":"JoynedButton","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}