{"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOpacity","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius"],"generated":true,"title":"Card UI Controls - Shadow"}],"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/shadowcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/shadowcolor"]}],"abstract":[{"type":"text","text":"The color to be used for card UI shadow color, only takes effect if the "},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","type":"reference"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Transperent by default."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@IBInspectable","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shadowColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"JoynedMobileSDK"}],"title":"shadowColor","role":"symbol","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton(py)shadowColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"shadowColor"}],"symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowColor"},"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowRadius":{"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius","abstract":[{"type":"text","text":"The radius of the shadow used by the card UI, only takes effect if the "},{"type":"reference","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","isActive":true},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Zero by default."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowradius","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"shadowRadius","navigatorTitle":[{"text":"shadowRadius","kind":"identifier"}],"role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"title":"JoynedMobileSDK","role":"collection","abstract":[{"text":"We help people book together. With a better booking experience, better business results","type":"text"}],"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","type":"topic","kind":"symbol","url":"\/documentation\/joynedmobilesdk"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowColor":{"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowColor","abstract":[{"text":"The color to be used for card UI shadow color, only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","isActive":true,"type":"reference"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Transperent by default."}],"url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowcolor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadowColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"title":"shadowColor","navigatorTitle":[{"kind":"identifier","text":"shadowColor"}],"role":"symbol"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowOpacity":{"navigatorTitle":[{"text":"shadowOpacity","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shadowOpacity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"abstract":[{"type":"text","text":"The opacity level of the shadow used by the card UI, only takes effect if the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Zero by default.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowopacity","type":"topic","title":"shadowOpacity","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOpacity"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton","abstract":[],"kind":"symbol","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","type":"topic","title":"JoynedButton","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoynedButton"}],"navigatorTitle":[{"kind":"identifier","text":"JoynedButton"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shadowOffset":{"navigatorTitle":[{"text":"shadowOffset","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shadowOffset","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"text":"The offset  of the shadow used by the card UI, only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","isActive":true,"type":"reference"},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Zero by default."}],"kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shadowoffset","type":"topic","title":"shadowOffset","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"kind":"article","abstract":[],"title":"Getting Started with Joyned mobile SDK","type":"topic","url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","role":"collectionGroup"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/isShadowEnabled":{"navigatorTitle":[{"text":"isShadowEnabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isShadowEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Determins if the card content should have a shadow outline or not, defaults to false"}],"kind":"symbol","role":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/isshadowenabled","type":"topic","title":"isShadowEnabled","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"shadowColor","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"shadowColor","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"replace","value":[{"generated":true,"title":"Card UI Controls - Shadow","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShadowEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOffset","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowOpacity","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shadowRadius"]}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"shadowColor","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"shadowRadius","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowRadius\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowRadius\/fragments","value":[{"text":"shadowRadius","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowColor\/title","value":"shadowColor","op":"replace"},{"value":[{"kind":"identifier","text":"shadowColor"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOpacity\/title","value":"shadowOpacity"},{"op":"replace","value":[{"text":"shadowOpacity","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOpacity\/fragments"},{"value":"JoynedButton","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","op":"replace","value":[{"text":"JoynedButton","kind":"identifier"}]},{"value":"shadowOffset","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOffset\/title"},{"value":[{"text":"shadowOffset","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shadowOffset\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShadowEnabled\/title","op":"replace","value":"isShadowEnabled"},{"value":[{"text":"isShadowEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShadowEnabled\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}