{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"shapeRadius"}],"title":"shapeRadius","roleHeading":"Instance Property","externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton(py)shapeRadius","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shapeRadius","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"modules":[{"name":"JoynedMobileSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@IBInspectable","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shapeRadius","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"The corner clipping radius, used for card UI clipping system. Only takes effect if the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","type":"reference"},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"]]},"kind":"symbol","seeAlsoSections":[{"title":"Card UI Controls - Clipping","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomRight","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight"],"generated":true}],"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shapeRadius","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/shaperadius"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/shaperadius"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipBottomLeft":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomLeft","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shouldClipBottomLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"shouldClipBottomLeft","kind":"identifier"}],"type":"topic","abstract":[{"text":"Indicates if the bottom left corner should be cliped or not, used for card UI clipping system.","type":"text"},{"text":" ","type":"text"},{"text":"Only takes effect if the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","type":"reference"},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"shouldClipBottomLeft","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomleft"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"abstract":[],"url":"\/documentation\/joynedmobilesdk\/joynedbutton","title":"JoynedButton","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JoynedButton","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JoynedButton"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipBottomRight":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomRight","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldClipBottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"shouldClipBottomRight"}],"type":"topic","abstract":[{"text":"Indicates if the bottom right corner should be cliped or not, used for card UI clipping system.","type":"text"},{"text":" ","type":"text"},{"text":"Only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","title":"shouldClipBottomRight","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomright"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipTopRight":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shouldClipTopRight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"shouldClipTopRight","kind":"identifier"}],"type":"topic","abstract":[{"text":"Indicates if the top right corner should be cliped or not, used for card UI clipping system.","type":"text"},{"type":"text","text":" "},{"text":"Only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"shouldClipTopRight","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldcliptopright"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/isShapeEnabled":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isShapeEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isShapeEnabled","kind":"identifier"}],"type":"topic","abstract":[{"text":"Determins if the card content should its corners cliped or not, defaults to false","type":"text"}],"role":"symbol","kind":"symbol","title":"isShapeEnabled","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/isshapeenabled"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","title":"Getting Started with Joyned mobile SDK"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipTopLeft":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldClipTopLeft","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"shouldClipTopLeft"}],"type":"topic","abstract":[{"text":"Indicates if the top left corner should be cliped or not, used for card UI clipping system.","type":"text"},{"text":" ","type":"text"},{"text":"Only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","title":"shouldClipTopLeft","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldcliptopleft"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shapeRadius":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shapeRadius","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shapeRadius","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"shapeRadius","kind":"identifier"}],"type":"topic","abstract":[{"text":"The corner clipping radius, used for card UI clipping system. Only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"shapeRadius","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shaperadius"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"role":"collection","title":"JoynedMobileSDK","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","url":"\/documentation\/joynedmobilesdk","kind":"symbol","abstract":[{"type":"text","text":"We help people book together. With a better booking experience, better business results"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"shapeRadius","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"shapeRadius","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"replace","value":[{"title":"Card UI Controls - Clipping","generated":true,"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomRight","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight"]}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"shapeRadius","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomLeft\/title","op":"replace","value":"shouldClipBottomLeft"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomLeft\/fragments","value":[{"kind":"identifier","text":"shouldClipBottomLeft"}]},{"value":"JoynedButton","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title"},{"value":[{"text":"JoynedButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments"},{"value":"shouldClipBottomRight","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomRight\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomRight\/fragments","value":[{"text":"shouldClipBottomRight","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopRight\/title","value":"shouldClipTopRight"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopRight\/fragments","value":[{"kind":"identifier","text":"shouldClipTopRight"}]},{"value":"isShapeEnabled","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShapeEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShapeEnabled\/fragments","value":[{"kind":"identifier","text":"isShapeEnabled"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopLeft\/title","value":"shouldClipTopLeft","op":"replace"},{"value":[{"kind":"identifier","text":"shouldClipTopLeft"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopLeft\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shapeRadius\/title","value":"shapeRadius","op":"replace"},{"value":[{"text":"shapeRadius","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shapeRadius\/fragments"}]}]}