{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"shouldClipBottomRight"}],"title":"shouldClipBottomRight","modules":[{"name":"JoynedMobileSDK"}],"externalID":"c:@M@JoynedMobileSDK@objc(cs)JoynedButton(py)shouldClipBottomRight","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shouldClipBottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"identifier":{"url":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomRight","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Indicates if the bottom right corner should be cliped or not, used for card UI clipping system.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Only takes effect if the "},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@IBInspectable","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldClipBottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","seeAlsoSections":[{"title":"Card UI Controls - Clipping","identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shapeRadius","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight"],"generated":true}],"variants":[{"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomright"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomright"]}],"references":{"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipTopLeft":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldClipTopLeft","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"shouldClipTopLeft"}],"type":"topic","abstract":[{"text":"Indicates if the top left corner should be cliped or not, used for card UI clipping system.","type":"text"},{"text":" ","type":"text"},{"text":"Only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","title":"shouldClipTopLeft","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldcliptopleft"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipBottomLeft":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomLeft","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shouldClipBottomLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"shouldClipBottomLeft","kind":"identifier"}],"type":"topic","abstract":[{"text":"Indicates if the bottom left corner should be cliped or not, used for card UI clipping system.","type":"text"},{"text":" ","type":"text"},{"text":"Only takes effect if the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","type":"reference"},{"type":"text","text":" is set to "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"shouldClipBottomLeft","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomleft"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shapeRadius":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shapeRadius","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shapeRadius","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"shapeRadius","kind":"identifier"}],"type":"topic","abstract":[{"text":"The corner clipping radius, used for card UI clipping system. Only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"shapeRadius","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shaperadius"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton":{"abstract":[],"url":"\/documentation\/joynedmobilesdk\/joynedbutton","title":"JoynedButton","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JoynedButton","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"JoynedButton"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipTopRight":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shouldClipTopRight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"shouldClipTopRight","kind":"identifier"}],"type":"topic","abstract":[{"text":"Indicates if the top right corner should be cliped or not, used for card UI clipping system.","type":"text"},{"type":"text","text":" "},{"text":"Only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"shouldClipTopRight","kind":"symbol","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldcliptopright"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/shouldClipBottomRight":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomRight","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldClipBottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"shouldClipBottomRight"}],"type":"topic","abstract":[{"text":"Indicates if the bottom right corner should be cliped or not, used for card UI clipping system.","type":"text"},{"text":" ","type":"text"},{"text":"Only takes effect if the ","type":"text"},{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","isActive":true,"type":"reference"},{"text":" is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","title":"shouldClipBottomRight","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/shouldclipbottomright"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK":{"role":"collection","title":"JoynedMobileSDK","type":"topic","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK","url":"\/documentation\/joynedmobilesdk","kind":"symbol","abstract":[{"type":"text","text":"We help people book together. With a better booking experience, better business results"}]},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/JoynedButton/isShapeEnabled":{"identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isShapeEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isShapeEnabled","kind":"identifier"}],"type":"topic","abstract":[{"text":"Determins if the card content should its corners cliped or not, defaults to false","type":"text"}],"role":"symbol","kind":"symbol","title":"isShapeEnabled","url":"\/documentation\/joynedmobilesdk\/joynedbutton\/isshapeenabled"},"doc://co.joyned.mobile.JoynedMobileSDK/documentation/JoynedMobileSDK/GettingStarted":{"url":"\/documentation\/joynedmobilesdk\/gettingstarted","identifier":"doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/GettingStarted","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","title":"Getting Started with Joyned mobile SDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"shouldClipBottomRight","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"shouldClipBottomRight"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"identifiers":["doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/isShapeEnabled","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shapeRadius","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipBottomLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopLeft","doc:\/\/co.joyned.mobile.JoynedMobileSDK\/documentation\/JoynedMobileSDK\/JoynedButton\/shouldClipTopRight"],"title":"Card UI Controls - Clipping","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldClipBottomRight"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopLeft\/title","value":"shouldClipTopLeft"},{"value":[{"kind":"identifier","text":"shouldClipTopLeft"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopLeft\/fragments"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomLeft\/title","value":"shouldClipBottomLeft","op":"replace"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomLeft\/fragments","op":"replace","value":[{"text":"shouldClipBottomLeft","kind":"identifier"}]},{"value":"shapeRadius","op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shapeRadius\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shapeRadius\/fragments","op":"replace","value":[{"kind":"identifier","text":"shapeRadius"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/title","value":"JoynedButton","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton\/fragments","value":[{"text":"JoynedButton","kind":"identifier"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopRight\/title","op":"replace","value":"shouldClipTopRight"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipTopRight\/fragments","op":"replace","value":[{"text":"shouldClipTopRight","kind":"identifier"}]},{"op":"replace","value":"shouldClipBottomRight","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomRight\/title"},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1shouldClipBottomRight\/fragments","op":"replace","value":[{"kind":"identifier","text":"shouldClipBottomRight"}]},{"path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShapeEnabled\/title","op":"replace","value":"isShapeEnabled"},{"value":[{"kind":"identifier","text":"isShapeEnabled"}],"op":"replace","path":"\/references\/doc:~1~1co.joyned.mobile.JoynedMobileSDK~1documentation~1JoynedMobileSDK~1JoynedButton~1isShapeEnabled\/fragments"}]}]}